name: Build and Deploy Frontend

on:
  push:
    branches: [ "main" ]

env:
  NODE_VERSION: '18.14.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code change
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
  
      - name: Install relevant npm dependencies
        run: npm install
  
      - name: Builds static files for push
        run: npm run build
        env:
          REACT_APP_QUOTES_API_KEY: ${{ secrets.QUOTES_API_KEY }}
        
      - name: Uploads artifact for use in deploy
        uses: actions/upload-artifact@v4
        with:
          name: markside_static_files
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download the static build files from artifact
        uses: actions/download-artifact@v4
        with:
          name: markside_static_files
          path: static-build/
      
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "static-build/"
          server-dir: "/"
